spring:
  datasource:
    url: jdbc:postgresql://db:5432/fda
    username: fda_admin
    password: fda_password
  sql:
    init:
      mode: embedded
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true
  writer-with-default-pretty-printer: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

fda:
  base-url: https://api.fda.gov
  connect-timeout-millis: 1000
  read-timeout-millis: 30000